# Generated by Django 3.2 on 2023-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20230709_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.SET(''), related_name='titles', to='titles.category'),
            preserve_default=False,
        ),
    ]
