# Generated by Django 3.2 on 2023-07-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_title_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
    ]
